services:
  hlds:
    image: cs:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
       USER_UID: ${USER_UID}
       USER_GID: ${USER_GID}
    container_name: hlds
    restart: unless-stopped
    environment:
      SERVER_IP: ${SERVER_IP}
      SERVER_PORT: ${SERVER_PORT}
      CLIENT_PORT: ${CLIENT_PORT}
      SV_LAN: ${SV_LAN}
      SYS_TICRATE: ${SYS_TICRATE}
      PING_BOOST: ${PING_BOOST}
      START_MAP: ${START_MAP}
      MAX_PLAYERS: ${MAX_PLAYERS}
    network_mode: host
    volumes:
      - ./store:/home/hlds/store/cstrike
      - ./server.cfg:/home/hlds/store/cstrike/server.cfg:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    cpuset: "0"
    mem_limit: "512m"

  fastdl:
    image: nginx:alpine
    container_name: fastdl
    restart: unless-stopped
    depends_on:
      - hlds
    ports:
      - "8283:80"
    volumes:
      - ./store/sound:/usr/share/nginx/html/cstrike/sound
      - ./store/maps:/usr/share/nginx/html/cstrike/maps
      - ./store/models:/usr/share/nginx/html/cstrike/models
      - ./store/gfx:/usr/share/nginx/html/cstrike/gfx
      - ./store/sprites:/usr/share/nginx/html/cstrike/sprites
      - ./store/overviews:/usr/share/nginx/html/cstrike/overviews
      - ./nginx/listing:/usr/share/nginx/html/listing
      - ./nginx/fastdl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
