name: Sync README to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   
          ref: main

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Save README.md
        run: cp README.md /tmp/index.md

      - name: Update gh-pages
        run: |
        
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi

          cp /tmp/index.md index.md

          git add index.md
          git commit -m "Update index.md from README.md" || echo "No changes"
          git push origin gh-pages
